version: '3'

services:
  v.infra:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  v.infra.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat

